### ISSUE TITLE
chat_url does is not present in the returned data from either getVideoInfo or getUserReplays

### ISSUE THREAD

**Issue by L2L2L** [thecoder75/liveme-api#9] opened 2017-11-05 21:32 UTC
I'm trying to get live chat feed data of my liveme account...
My code:
```
var livemeapi = require('../index'), return_code = 0;

livemeapi.getLiveGirls(1,1)
	.then(results => {
		console.log("perform search: ")
		var arr = results.video_info.map((obj,indx)=>{
			return {uname:obj.uname,
					userid:obj.userid,
					vdoid:obj.vdoid,
					vid:obj.vid,
					online:obj.online};
		});
		livemeapi.getVideoInfo(arr[2].vid)
		.then(vidInfo=>{
			console.log("video info:", vidInfo);
			console.log("chat history: ");
			console.log(livemeapi.getChatHistoryForVideo(vidInfo.chat_url));
		});
		
	})
	.catch(err => {
		console.log(`performSearch() hashtag test failed, ${err}`);
		return_code = 1;
	});

return return_code;
```

**Comment by L2L2L** [comment] 2017-11-05 23:33
```
var livemeapi = require('../index'), return_code = 0;

livemeapi.getLiveGirls(1,1)
	.then(results => {
		console.log("performSearch: ")
		var arr = results.video_info.map((obj,indx)=>{
			return {uname:obj.uname,
						userid:obj.userid,
						vdoid:obj.vdoid,
						vid:obj.vid,
						online:obj.online};
		});
		livemeapi.getVideoInfo(arr[2].vid)
		.then(vidInfo=>{
			console.log("videoInfo:", vidInfo);
			console.log("\nchat history: \n",vidInfo.gzip_msgfile);
			livemeapi.getChatHistoryForVideo(vidInfo.gzip_msgfile);
		}).catch(err=>{console.log(err);});
		
	})
	.catch(err => {
		console.log(`performSearch() hashtag test failed, ${err}`);
		return_code = 1;
	});

return return_code;
```

output:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 403
```

The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it.
# 
Is it possible despite this to gain access to one chat live feed? 

for both

**Comment by thecoder75** [comment] 2017-11-06 01:34
Looking at your code you need to pass `vidInfo.msgfile` to the `getChatHistoryForVideo` for it to work.  Passing `vidInfo.gzip_msgfile` will fail every time as the command only looks and is able to process uncompressed version of the message file.

**Comment by L2L2L** [comment] 2017-11-06 02:33
Thank you for replying. I did both before I post that. I use both msgfile and gzip_msgfile. both are returning a 403 status code. Maybe the right permission is not there.

**Comment by thecoder75** [comment] 2017-11-06 02:36
What version of the API are you running?  There was an authentication error with both getting video details and with getting the message history for a video that was fixed in the latest release.

**Comment by thecoder75** [comment] 2017-11-06 02:38
Also are you running under Node or Electron or NWjs?  If so, what version are you running?

**Comment by L2L2L** [comment] 2017-11-06 05:26
```
l2l2l:~/workspace $ npm liveme-api -v
3.10.10
l2l2l:~/workspace $ node -v
v6.11.2
```

**Comment by thecoder75** [comment] 2017-11-06 18:14
Okay figured out what is going on.  You're trying to get the message history for a **Live** feed.  This cannot be done as the file hasn't been written and released yet which will cause the 403 error.

The command can only be used to get the message history for a replay (previously recorded) feed.

Since this is not a bug in the code but an attempt to use the command not as it was designed or intended to be used, I'm considering this issue closed.

**Closed by thecoder75** 2017-11-06 18:14 UTC
Labels: discussion, invalid
